### ISSUE TITLE
employee weekly off day(s)?

### ISSUE THREAD

**Issue by cagriguerbuez** [opengovsg/ctrl-shift#51]
Hello, 

I just added "weekOfDay" of a person to Employee entity, and trying to make the Employee UNAVAILABLE on the thay specified with entity.

One way is to write a rule, other is to set unavailability with each rotation (from the beggining).

I'm confused here, because already a rule exist to check of unavailability of a employee, I don't want to write same rule and jsut make it to check whether the day is the "weekOfDay" or not. But, I couldn't achieve to make second option?

Any help on that?

Thanks in advance.

**Comment by LoneRifle** [comment]
Hey @cgrgrbz - I recognise you from the optaplanner-dev forum. Your issues are probably better addressed there. It's not clear from your opening post exactly what problems you are running into when trying to do the "second option" (are you trying to modify the existing rule to account for both unavailability in the database as well as unavailability implied by `dayOfWeek`?). If I were you, I would avoid having such a field in the Employee entity and instead figure a way to quickly create and duplicate an employee's availability across multiple weeks. Hope that helps!
